version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gkexpress
      POSTGRES_USER: gkuser
      POSTGRES_PASSWORD: secretpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: