spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/gkexpress?options=-c%20timezone=UTC
    username: gkuser
    password: secretpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false